#ifndef COM_GSRPC_TEST_TEST_GS
#define COM_GSRPC_TEST_TEST_GS
#import <com/gsrpc/stream.h>

#import <com/gsrpc/channel.h>


@class GSTestRemoteException;

@class GSTestBlock;

typedef enum GSTestTimeUnit:UInt8 GSTestTimeUnit;

@class GSTestDuration;

@class GSTestKV;

@class GSTestNotFound;


@interface GSTestRemoteException : NSObject

+ (instancetype)init;
- (void) marshal:(id<GSWriter>) writer;
- (void) unmarshal:(id<GSReader>) reader;
- (NSError*) asNSError;
@end



//GSTestRESTful generate by objrpc
@protocol GSTestRESTful<NSObject>

- (void) Post:(NSString*)arg0 withArg1:(NSMutableData *)arg1;

- (NSMutableData *) Get:(NSString*)arg0;

@end

// GSTestRESTfulService generate by objrpc
@interface GSTestRESTfulService : NSObject<GSDispatcher>
+ (instancetype) init:(id<GSTestRESTful>)service withID:(UInt16) serviceID;

@property(readonly) UInt16 ID;

- (GSResponse *)Dispatch:(GSRequest *)call;

@end


@interface GSTestRESTfulRPC : NSObject
+ (instancetype) initRPC:(id<GSChannel>) channel withID:(UInt16) serviceID;

- (id<GSPromise>) Post:(NSString*) arg0  withArg1:(NSMutableData *) arg1 ;

- (id<GSPromise>) Get:(NSString*) arg0 ;

@end



// GSTestBlock generated by objrpc tools
@interface GSTestBlock : NSObject

@property(nonatomic, strong) NSMutableData * Content;

@property(nonatomic, strong) NSMutableArray * KV;

+ (instancetype)init;
- (void) marshal:(id<GSWriter>) writer;
- (void) unmarshal:(id<GSReader>) reader;
@end



// GSTestTimeUnit enum
enum GSTestTimeUnit:UInt8{ 
	GSTestTimeUnitSecond = 0
 };

// GSTestTimeUnit enum marshal/unmarshal helper interface
@interface GSTestTimeUnitHelper : NSObject
+ (void) marshal:(GSTestTimeUnit) val withWriter:(id<GSWriter>) writer;
+ (GSTestTimeUnit) unmarshal:(id<GSReader>) reader;
+ (NSString*) tostring :(GSTestTimeUnit)val;
@end



// GSTestDuration generated by objrpc tools
@interface GSTestDuration : NSObject

@property SInt32 Value;

@property GSTestTimeUnit Unit;

+ (instancetype)init;
- (void) marshal:(id<GSWriter>) writer;
- (void) unmarshal:(id<GSReader>) reader;
@end



// GSTestKV generated by objrpc tools
@interface GSTestKV : NSObject

@property(nonatomic, strong) NSString* Key;

@property(nonatomic, strong) NSString* Value;

+ (instancetype)init;
- (void) marshal:(id<GSWriter>) writer;
- (void) unmarshal:(id<GSReader>) reader;
@end



@interface GSTestNotFound : NSObject

+ (instancetype)init;
- (void) marshal:(id<GSWriter>) writer;
- (void) unmarshal:(id<GSReader>) reader;
- (NSError*) asNSError;
@end


#endif //COM_GSRPC_TEST_TEST_GS
